tech:
  device: "cpu"
  seed: 228
environment:
  num_consumers: 15
  num_firms: 8
  labour_disutility: 0.01
  crra_uf_param: 0.1
  investments_percent: 0.1
  discount_factor: 0.9
  timesteps: 10
  epochs: 1
  inital:
    firm_budget: 2200000
    items_q: 0
    items_p: 0
    taxes: 0.0
consumer:
  model:
    mlp_layer_width: 128
    num_items: 11
    working_hours:
      min: 0
      max: 1040
      step: 260
  optimizer:
    lr: 0.001
  reward_scaling_factor: 5
firm:
  model:
    mlp_layer_width: 128
    prices:
      min: 0
      max: 2500
      step: 500
    wages:
      min: 0
      max: 44
      step: 11
  optimizer:
    lr: 0.001
  reward_scaling_factor: 30000
government:
  model:
    mlp_layer_width: 128
    taxes:
      min: 0.0
      max: 1.0
      step: 0.2
  optimizer:
    lr: 0.0005
  reward_scaling_factor: 1000