tech:
  device: "cpu"
  seed: 228
environment:
  num_consumers: 48
  num_firms: 8
  labour_disutility: 0.01
  crra_uf_param: 0.1
  investments_percent: 0.1
  discount_factor: 0.75
  timesteps: 15
  epochs: 15
  inital:
    firm_budget: 22000000
    items_q: 0
    items_p: 0
    taxes: 0.0
consumer:
  model:
    mlp_layer_width: 128
    num_items: 6
    working_hours:
      min: 0
      max: 520
      step: 130
  optimizer:
    lr: 0.001
  reward_scaling_factor: 5
firm:
  model:
    mlp_layer_width: 128
    prices:
      min: 0
      max: 1000
      step: 200
    wages:
      min: 0
      max: 44
      step: 11
  optimizer:
    lr: 0.001
  reward_scaling_factor: 30000
government:
  model:
    mlp_layer_width: 128
    taxes:
      min: 0.0
      max: 1.0
      step: 0.2
  optimizer:
    lr: 0.0005
  reward_scaling_factor: 1000