tech:
  device: "cpu"
  seed: 1488
environment:
  num_consumers: 48
  num_firms: 8
  labour_disutility: 0.01
  crra_uf_param: 0.1
  investments_percent: 0.1
  discount_factor: 0.8
  timesteps: 45
  epochs: 100
  epochs_firms: 50
  epochs_government: 80
  initial:
    firm_budget: 22000000
    consumer_budget: 0
    items_q: 0
    items_p: 1000
    taxes: 0.0
consumer:
  model:
    mlp_layer_width: 128
    num_items: 5
    working_hours:
      min: 0
      max: 1040
      step: 260
  optimizer:
    lr: 0.01
  reward_scaling_factor: 25.0
firm:
  model:
    mlp_layer_width: 128
    prices:
      min: 0
      max: 2500
      step: 500
    wages:
      min: 0
      max: 44
      step: 11
  optimizer:
    lr: 0.00005
  reward_scaling_factor: 300000.0
government:
  model:
    mlp_layer_width: 128
    taxes:
      min: 0.0
      max: 1.0
      step: 0.2
  optimizer:
    lr: 0.0001
  reward_scaling_factor: 1.0